# -*- coding: utf-8 -*-
"""P19337.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MOqEevYPZGuY7MKQ826yZunw0uAT_1XI
"""

from RPSLS_player import RPSLS_player
import random
a = [1,2,3,4,5]
n = random.choice(a)

class P19337(RPSLS_player):
    def __init__(self, paper, rock, scissors, spock, lizard):
      self.paper = paper
      self.rock = rock
      self.scissors = scissors
      self.spock = spock
      self.lizard = lizard

    def shoot(self):

        if a == 1 :
            return 'paper'
        if a == 2 :
            return 'rock'
        if a == 3 :
            return 'scissors'
        if a == 4 :
            return 'spock'
        if a == 5 :
            return 'lizard'
  
    def update(self, result: str, competitor_shot: str):
        pass



